version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel_app
    restart: always
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_KEY: ${APP_KEY:-base64:$(openssl rand -base64 32)}
      APP_URL: http://localhost:8000
    # Añade estas líneas para manejar migraciones
    command: >
      bash -c "php artisan migrate:fresh --seed --force
      && apache2-foreground"